[project]
name = "home-ops-copilot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.2",
    "fastapi>=0.128.0",
    "openai>=2.14.0",
    "pydantic-settings>=2.12.0",
    "ragas>=0.4.2",
    "uvicorn>=0.40.0",
]
